import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Banner from '../components/Banner'
import Dailyevents from '../components/Dailyevents'
import Theme from '../components/Theme'

export default function Home() {
  return (
    <div>
      <Head>
        <title>TechnoVIT'22</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="home">
        <Banner />
      </div>
      <div>
        <Theme />
      </div>
      <div id="about">
        <About />
      </div>
      <div id="events">
        <Dailyevents />
      </div>
    </div>
  )
}
