import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Dailyevents from '../components/Dailyevents'
import Theme from '../components/Theme'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>TechnoVIT'22</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />
      <Theme />
      <Dailyevents />
    </div>
  )
}
