import Head from 'next/head'
import About from '../components/About'
import Banner from '../components/Banner'
import Conveners from '../components/Conveners'
import Dailyevents from '../components/Dailyevents'
import Footer from '../components/Footer'
import Schoolevent from '../components/Schoolevent'
import Theme from '../components/Theme'

export default function Home() {
  return (
    <div>
      <Head>
        <title>TechnoVIT'22</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="home">
        <Banner />
      </div>
      <div>
        <Theme />
      </div>
      <div id="about">
        <About />
      </div>
      <div id="events">
        <Dailyevents />
      </div>
      <div id="schools">
        <Schoolevent />
      </div>
      <div id="conveners">
        <Conveners />
      </div>
      <div id="footer">
        <Footer />
      </div>
    </div>
  )
}
